#!/bin/bash
bee=bee-0.45.0.far
if [ ! -f "$bee" ]; then
    if [ -n "$JAVA_HOME" ]; then
        bee="$JAVA_HOME/lib/bee/bee-0.45.0.jar"
    else
        # Try to infer JAVA_HOME from PATH
        java_path=$(command -v java)
        if [ -n "$java_path" ]; then
            javaDir=$(dirname "$java_path")
            bee="$javaDir/../lib/bee/bee-0.45.0.jar"
        fi
    fi
    if [ ! -f "$bee" ]; then
        echo "bee is not found locally, try to download it from network."
        curl -#L -o "$bee" --create-dirs https://jitpack.io/com/github/teletha/bee/0.45.0/bee-0.45.0.jar
    fi
fi
java -javaagent:"$bee" -cp "$bee" bee.Bee "$@"