#!bin/bash
bee=$JAVA_HOME/lib/bee-0.13.0.jar
if [ ! -e $bee ]; then
  echo $bee is not found, try to download it from network.
  curl -#L -o $bee https://jitpack.io/com/github/teletha/bee/0.17.2/bee-0.17.2.jar
fi
java -javaagent:$bee -cp $bee bee.Bee "$@"
